- spine-cocos2dx/3/src/spine/SkeletonAnimation.cpp
- spine-cocos2dx/3/src/spine/SkeletonAnimation.h
- spine-cocos2dx/3/src/spine/SkeletonRenderer.cpp
- spine-cocos2dx/3/src/spine/SkeletonRenderer.h
Hi.
These changes are needed for supporting **extend** of this classes in [Cocos2d-x Javascript Binding](https://github.com/cocos2d/cocos2d-js):
1. All constructors and init methods must be in ```CC_CONSTRUCTOR_ACCESS``` scope instead of ```protected``` because of **JSB** binding generator`s needs;
2. I'm add init functions for all constructors of ```SkeletonRenderer``` because we need to init the class after calling empty constructor (That is how **JSB** works).
We can't modify sources of **spine-runtimes** according to the license conditions so in  [Cocos2d-x Javascript Binding](https://github.com/cocos2d/cocos2d-js) we very need these changes.
Hope you understand.
Thanks.
> Cocos2d-x: changes for JSB support.

- spine-js/spine.js
Adds support for typed arrays (float32 and uint16), useful when rendering in WebGL.
Fixes syntax issues in the `updateUVs` functions in MeshAttachment and SkinnedMeshAttachment.
Tested in pixi.js:
> [JS] Mesh attachments + syntax fixes + infinite loop fix

- spine-cocos2d-iphone/3/README.md
- directory has been changed from 3.0 to just 3
- the example objective-c files end in .m not .cpp
- the runtime requires CCRenderer, which I believe is only available in 3.1+
> Readme fixes

- spine-cocos2d-iphone/2/README.md
The example links were to .cpp files, but it should be .m
> Fixing links to examples

- spine-lua/SkinnedMeshAttachment.lua
The SkinnedMeshAttachment.lua returns "MeshAttachment" instead of SkinnedMeshAttachement which results in silently returning a nil value
> return the proper local for the module

- spine-c/src/spine/IkConstraint.c
Was not working without SPINE_SHORT_NAMES defined.
> spine-c compile fix

- spine-js/spine.js
Atlas attachment loader was using the name as the path to the images in the atlas instead of the path argument passed to it. It would throw an exception using the path argument to report the error, making it extremely confusing. It now properly uses the path argument to look for the image.
This bug made it a requirement to have images and attachments that held them have the same name, not very visible bug in spine because the editor names things properly most of the time but with a more strict naming convention this bug is very evident.
I believe that this bug is present in other runtimes, further investigation is needed.
> [JAVASCRIPT] Atlas attachment loader fix.

- spine-c/src/spine/SkeletonJson.c
Missing space for `\0`
Problem has been highlighted during loading invalid json.
> Fix buffer overflow when JSON Skeleton produces Error

- spine-c/include/spine/Animation.h
- spine-c/include/spine/AnimationState.h
- spine-c/include/spine/AnimationStateData.h
- spine-c/include/spine/Attachment.h
- spine-c/include/spine/Bone.h
- spine-c/include/spine/BoneData.h
- spine-c/include/spine/Event.h
- spine-c/include/spine/EventData.h
- spine-c/include/spine/IkConstraint.h
- spine-c/include/spine/IkConstraintData.h
- spine-c/include/spine/Skeleton.h
- spine-c/include/spine/Skin.h
- spine-c/include/spine/Slot.h
- spine-c/include/spine/SlotData.h
- spine-c/include/spine/extension.h
for Visual Studio compiler compatibility where projects are using C++
----------------
spine-c now compiles successfully in VS 2013!
I don't know what I'm doing with regards to what values to use for initialization.  most things are ints, floats, chars or pointers so I set them to 0 and hope that it will all work out somehow. I think they will all be overwritten by your custom OO create methods but I'm not sure how that all works. Maybe take a cursory glance at that? Also the super() inits, did I do those right?
> add C++ constructors to all structs (VS Compiler C++ compatibility)

- spine-unity/Assets/spine-unity/Editor/SkeletonDataAssetInspector.cs
- spine-unity/Assets/spine-unity/SkeletonDataAsset.cs
I just recently switched from using the old spine-tk2d runtime to using the latest spine-unity runtime. This change caused all my skeletons to render at exactly 100x size. There was an explicit *100f at SkeletonDataAsset.cs:111 which doesn't seem to have a reason to be there (corroborated by [this thread](http://esotericsoftware.com/forum/spine-unity-ignore-tk2d-pixel-per-meter-setting-4233)) so I removed that, which fixed the in-game render size.
After making that change, the Inspector preview window for a SkeletonDataAsset stopped rendering if the **scale** property there was anything higher than about 0.18 (it defaults to 1). This doesn't make a lot of sense to me, but the condition at SkeletonDataAssetInspector.cs:651 did seem to be the culprit, so I changed that and it seems to work …
> Fix for unexpected huge skeleton render scale when using SPINE_TK2D

- spine-csharp/spine-csharp.csproj
Not sure why github's text editor changed that bottom part. But it did. Must be a line endings thing.
> Add ExposedList.cs to C# csproj.

- spine-csharp/src/AnimationState.cs
Not sure if the same "fix" needs to be applied to other runtimes, or if this was intended behavior at all. But someone in the forums was looking for this fix.
> [C#] Optional fix for firing events when mixing

- spine-csharp/src/Json.cs
There is a problem in turning `JsonDecoder` into a singleton: it uses `lexer` field that is modified by each call to `Decode`, so any already running `Decode` will suffer because its `lexer` will be lost.
Btw there is no big performance gain in previous solution (I assume it was done that way for optimization reasons). Premature optimization is the root of all evil :smile: 
PS: Another option would be to rewrite `SharpJson` a bit to pass the `lexer` explicitly instead of storing it in the field.
> Make Json.Deserialize thread-safe in spine-csharp

- spine-lua/Animation.lua
- spine-lua/AttachmentLoader.lua
- spine-lua/MeshAttachment.lua
- spine-lua/SkeletonJson.lua
- spine-lua/SkinnedMeshAttachment.lua
Minor fixes for off-by-one indexing and loop counts for skinned meshes
Some fixes for names or counts, again for skinned meshes
(This does not include the mesh logic itself, nor have I tested basic meshes.)
> Added requires in attachment loader

- .gitignore
- spine-monogame/xamarinstudio-ios/example/AppDelegate.cs
- spine-monogame/xamarinstudio-ios/example/Main.cs
- spine-monogame/xamarinstudio-ios/example/packages.config
- spine-monogame/xamarinstudio-ios/example/spine-monogame-example.csproj
- spine-monogame/xamarinstudio-ios/example/spine-monogame-example.sln
- spine-monogame/xamarinstudio-ios/src/packages.config
- spine-monogame/xamarinstudio-ios/src/spine-monogame-xamarinstudio-ios.csproj
- spine-monogame/xamarinstudio-ios/src/spine-monogame-xamarinstudio-ios.sln
- spine-xna/example/src/ExampleGame.cs
* Migrate to unified API to support 64 bit platforms.
* Remove call to game.exit() in ExampleGame.cs as this is no longer supported.
* Use MonoGame.ios Nuget package instead of relying on external repo being present on the machine.
> Update MonoGame iOS example in line with recent changes.

- spine-lua/RegionAttachment.lua
nil is the actual keyword. 'null' works in non strict mode as all undeclared variables are considered 'nil' in non strict mode.
> [LUA] Change null to nil

- spine-csharp/src/Animation.cs
- spine-csharp/src/Attachments/AttachmentType.cs
- spine-csharp/src/Attachments/IFfdAttachment.cs
- spine-csharp/src/Attachments/MeshAttachment.cs
- spine-csharp/src/Attachments/WeightedMeshAttachment.cs
- spine-csharp/src/Bone.cs
- spine-csharp/src/IkConstraint.cs
- spine-csharp/src/SkeletonBinary.cs
- spine-csharp/src/SkeletonJson.cs
**FfdTimeline.Apply**
Used an `as` then `null` check instead of an `is` then `as`.
This is recommended usage and gets highlighted by IDEs.
**SkeletonJson**
Instead of a Java static class `LinkedMesh`, it is an internal class with internal members. Java's "static" nested class means something totally different.
**SkeletonBinary**
Since the LinkedMesh class is defined in SkeletonJson, SkeletonJson's linkedMeshes field is of type `List<LinkedMesh>` but SkeletonBinary's is `List<SkeletonJson.LinkedMesh>`.
Unlike in Java, the class name needs to be fully qualified with the name of the parent class every time it's used. I think C#6 allows this with the `using` keyword but this is not supported by Unity's older compiler.
**WeightedMeshAttachment** and **MeshAttachment**
The `ParentMesh` property …
> Updated spine-csharp to 3.1.05: linked meshes.

- spine-js/spine.js
Float32Array.length is read only and will not resize the array. This caused the .length to always be 0 and thus not use ffd in spine.WeightedMeshAttachment.computerWorldVertices(). This proposed fix instead creates a new array when the size has changed.
> [spine-js] Fixed a bug where ffd would never be used in "computeWorldVertices".

- spine-c/src/spine/Animation.c
Hello, I get the following `-Wshadow` warning when compiling spine-c runtime with Xcode 7.3 and Clang:
```
spine/Animation.c:270:9: Declaration shadows a local variable
```
This PR fixes it. Thanks!
> Fix -Wshadow warning when compiling with Clang

- spine-lua/AnimationState.lua
Fixes what I believe to be two bugs in the lua runtime AnimationState.
1) Adding an animation on an empty track will now play the animation. This is Line 214
2) The rest of the updates make trackCount hold count and not max track index as it previously did. This fixes an error where animations on the highest track index would stop if the second highest track index finished its animations and cleared the track.
Tested using modified SpineBoy example in main.lua in spine-love using the above mentioned use cases.
> [LUA] AnimationState trackCount bugfixes

- spine-unity/Assets/spine-unity/Modules/SpriteAttacher.cs
The case here is as follows:
- create random unity sprite prefab
- place sprite's pivot point outside of the sprite (say, pivot U is 2.53 and pivot V is -1.22)
- try to attach this sprite via the SpriteAttacher script
Expected result here would be seeing the sprite sticking with it's pivot point to the placeholder.
Actual result here looks like the sprite's pivot point is somewhere in U: 1 and V: 0.
The bug is caused by Mathf.InverseLerp - it just cannot return values outside of [0; 1] range.
So the solution would be to make our own version of InverseLerp, which handles such situations correctly.
> [spine-unity] Support sprite attachments with pivot placed outside the sprite

- spine-csharp/src/Attachments/VertexAttachment.cs
- spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/attachments/VertexAttachment.java
Postincrement affects its variable only when entire expression is evaluated.
The same fix for spine-c is here: https://github.com/EsotericSoftware/spine-runtimes/pull/624#issuecomment-229898936
> [csharp][libgdx] fix iterating bones in VertexAttachment.ComputeWorldVertices.

- spine-c/src/spine/Bone.c
* crashes when bone has no parent
* doesn't calculate local rotation when bone has parent
I stumbled upon this while porting 3.4 to spinecpp :)
> [spine-c] Fixed spBone_worldToLocalRotationY

- spine-c/src/spine/Skeleton.c
```==13599==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000d770 at pc 0x605362 bp 0x7ffec4ab41b0 sp 0x7ffec4ab41a0
READ of size 8 at 0x60200000d770 thread T0
#0 0x605361 in spSkeleton_create thirdparty/spine-c/source/common/Skeleton.c:67```
> Fixed error reported by address sanitizer 

- spine-as3/spine-as3/src/spine/animation/Listeners.as
Hello,
Just a couple of changes.
The change in add() will make sure a callback is never registered twice (slight change of behavior, consistent with the signals library, seems harmless to me).
The change in remove() will make sure that a listener is in the list before removing it (this one fix a bug, if indexOf == -1 then splice will remove the wrong listener).
Thanks for the hardwork !
> [as3] Fix strange behaviour of listeners

- spine-lua/AttachmentLoader.lua
Corona SDK was throwing the following error:
File: spine-lua/AttachmentLoader.lua
Line: 46
Attempt to index global 'MeshAttachment' (a nil value)
> [LUA] Added missing require

- spine-c/src/spine/SkeletonJson.c
* The json structure is that the path constraint timelines are added per path constraint
* Instead of the number of timelines what was calculated was the number of path constraints for which we have timelines
* If there were more timelines than path constraints, this led to memory corruption (writing past the buffer)
> [spine-c] Fixed calculation of number of path constraint timelines.

- spine-c/src/spine/PathConstraint.c
* First space of path constraint spaces remained uninitialized
* This led to various visual bugs with path constraints
> [spine-c] Fixed uninitialized value

- spine-starling/spine-starling/src/spine/starling/SkeletonSprite.as
Instead of setting color and alpha on each vertex, call colorize() only once before iterating through all vertices.
In our use case, performances are multiplied by 2.
> Improved performances when applying color and alpha on vertices

- spine-cocos2dx/src/spine/spine-cocos2dx.cpp
This pull request adds missing switch case `SP_ATLAS_UNKNOWN_FILTER` to prevent the following warning on Xcode 7.3.1 (Clang).
```
spine-cocos2dx.cpp:42:10: Enumeration value 'SP_ATLAS_UNKNOWN_FILTER' not handled in switch [-Wswitch]
```
> [cocos2d-x] Add missing switch case

- spine-c/include/spine/extension.h
When trying to compiling Spine 3.4 with cocos2d-x v3.13 (in progress) on Xcode 7.3.1/Clang, I get the following warnings:
```
extension.h:86:9: 'MIN' macro redefined
extension.h:87:9: 'MAX' macro redefined
```
The CCStdC header has defined `MIN` and `MAX` macros but those macros are defined unconditionally in `extension.h` as follows:
- [cocos2d-x/cocos/platform/ios/CCStdC-ios.h#L43-L49](https://github.com/cocos2d/cocos2d-x/blob/294596861436c918b08a7f4efa9f321890c991f9/cocos/platform/ios/CCStdC-ios.h#L43-L49)
- [cocos2d-x/cocos/platform/mac/CCStdC-mac.h#L43-L49](https://github.com/cocos2d/cocos2d-x/blob/294596861436c918b08a7f4efa9f321890c991f9/cocos/platform/mac/CCStdC-mac.h#L43-L49)
So this pull request adds `#ifndef MIN` and `#ifndef MAX` conditions to fix the warnings.
Thank you for …
> [spine-c] Fix redefinition of macro MIN and MAX

- spine-c/src/spine/VertexAttachment.c
This pull request prevents the following compiler warnings being issued when compiling with Xcode 7.3.1 and Clang.
```
VertexAttachment.c:77:8: declaration shadows a local variable [-Wshadow]
VertexAttachment.c:97:8: declaration shadows a local variable [-Wshadow]
VertexAttachment.c:97:11: declaration shadows a local variable [-Wshadow]
VertexAttachment.c:97:17: declaration shadows a local variable [-Wshadow]
```
> [spine-c] Prevent variable shadowing warnings

- spine-c/src/spine/SkeletonJson.c
Hi, I get this warning when compiling spine-c from within cocos2d-x v3.13 (in progress) on Xcode 7.3.1:
```
SkeletonJson.c:835:10: declaration shadows a local variable [-Wshadow]
```
This pull request fixes it.
> [c] Fix variable shadowing warning

- spine-c/src/spine/SkeletonBinary.c
Hello!
We've found one another memory leak with linked meshes: https://github.com/EsotericSoftware/spine-runtimes/commit/79f1952ed9bf5090d593f5805ac7669480017981
Also I've included fixes specified in https://github.com/EsotericSoftware/spine-runtimes/issues/696#issuecomment-248024122 for your convinience. Thanks to @balmerdx!
I will check it with [valgrind](http://valgrind.org/) as soon as possible to find another memory issues. Sorry for that, I've should do it in the first place :disappointed:
> [c] binary skeleton leaks

- spine-cocos2dx/src/spine/SkeletonRenderer.cpp
Currently valgrind reports the following error:
==3357== Mismatched free() / delete / delete []
==3357==    at 0x4C2B1C6: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3357==    by 0x199EDB9: spine::SkeletonRenderer::~SkeletonRenderer() (SkeletonRenderer.cpp:101)
The memory which `_worldVertices` points to gets allocated in [SkeletonRenderer.cpp#L64](https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-cocos2dx/src/spine/SkeletonRenderer.cpp#L64), and therefore a `delete []` must be used instead. Otherwise we might get undefined behavior on some devices.
> Fix mismatched memory deallocator in SkeletonRenderer.cpp

- spine-c/src/spine/AnimationState.c
When using events with large string data, the allocated memory for event is too small to store the event data. It will overflow and cause heap corruption.
It has solved our random crash problem in a game with millions of users.
> [spine-c] Allocate more memory for events to prevent heap corruption

- spine-c/spine-c/src/spine/Atlas.c
In brief, the 'isspace' function allows a *unsigned* value between 0 and 255, while char is signed by default, so a char code over 0x80 represents a negative value which caused a assertion in the 'isspace' function.
The workaround is force converting the char into unsigned char.
> Fix a bug caused a crash on VS2013 or later when in Debug mode if there is any Unicode chars such as Chinese in Atlas file.

- spine-c/spine-c/src/spine/AnimationState.c
- spine-c/spine-c/src/spine/Skeleton.c
Would be cool to have those type casts added, my guess is those can also happen on other compilers.
- Added type cast to spEventType from AnimationState objects
- Added type cast to void-type realloc calls in Skeleton.c
> Android NDK r10d  wouldn't compile, blamed wrong types

- spine-ue4/Plugins/SpinePlugin/Source/SpinePlugin/Public/SpineSkeletonAnimationComponent.h
- spine-ue4/Plugins/SpinePlugin/Source/SpinePlugin/Public/SpineSkeletonComponent.h
Without this, line 52 (now line 53) of SpineSkeletonComponent.h would throw an error not recognizing USpineSkeletonDataAsset.
Also, attempting to use GetTrackEntry() from SpineSkeletonAnimationComponent.h would throw a Linker error as the behavior was not defined.
> [ue4] Made compiling in VS work; defined behavior for GetTrackEntry()

- spine-starling/spine-starling/src/spine/starling/SkeletonSprite.as
This problem was probably introduced while moving to new starling version where premultiplied alpha is no longer passed as an argument to `render()`. 
BTW if I get it right then there's no need to manually restore `blendMode` because `DisplayObjectContainer` wraps child's `render()` with `painter.pushState()`/`painter.popState()`.
> [as3] animation totally disappears if has alpha < 1

- spine-ts/widget/src/Widget.ts
When using Widget with React and other frameworks it's common to change properties but reuse the same DOM element. But when creating a new widget while reusing the same DOM element, spine-widget creates a new canvas object each time. This results in one element containing many canvases at once. 
This solution checks for an existing canvas to use instead of assuming a new one needs to be created each time. Makes Widget much more React friendly.
> reuse existing canvas element when possible

- spine-ue4/Plugins/SpinePlugin/Source/SpineEditorPlugin/SpineEditorPlugin.Build.cs
- spine-ue4/Plugins/SpinePlugin/Source/SpinePlugin/SpinePlugin.Build.cs
- spine-ue4/Source/SpineUE4.Target.cs
- spine-ue4/Source/SpineUE4/SpineUE4.Build.cs
- spine-ue4/Source/SpineUE4Editor.Target.cs
Any project using ue4-spine plugin fails to build on UE 4.16.x unless the build system is modified according to the new changes in the UE4 build system.
> [ue4] make the plugin build on UE 4.16.x
