EsotericSoftware/spine-runtimes

spine-unity/Assets/spine-unity/Editor/SkeletonRendererInspector.cs, spine-unity/Assets/spine-unity/SkeletonRenderer.cs
Added "Front Facing" parameter to SkeletonRenderer
=> Null mesh cleanup fixed in SkeletonRenderer

spine-unity/Assets/spine-unity/SkeletonRenderer.cs
Cached slot.bone to remove 3 dereferences.
=> Unnoticeably faster frontFacing SkeletonRenderer

spine-starling/spine-starling/src/spine/starling/SkeletonSprite.as
Hi,
I dont think you need to apply the scales here because it will be done automatically by the framework (the localPoint is already transformed in the locales coordinates)
Have a nice day!
Seb
=> Fix issue with HitTest

spine-monogame/windows8-store/example/spine-monogame-example.csproj, spine-monogame/xamarinstudio-ios/example/spine-monogame-example.csproj
Small change - goblins file had been renamed, so just needed to update the references in the two monogame projects.
=> Fix monogame example program

spine-unity/Assets/spine-unity/Editor/SkeletonAnimationInspector.cs, spine-unity/Assets/spine-unity/Editor/SkeletonRendererInspector.cs
Added Sorting Layers interface to Spine-Unity SkeletonRenderer and SkeletonAnimation editor inspectors.
Also added foldout/collapsible for the advanced options like Calculate Normals, Front Facing, etc...
=> Added Sorting Layers GUI to SkeletonRenderer and SkeletonAnimation

spine-unity/Assets/spine-unity/SkeletonExtensions.cs, spine-unity/Assets/spine-unity/SpriteAttacher.cs, spine-unity/Assets/spine-unity/SpriteAttacher.cs.meta
=> SpriteAttachmentLoader

spine-unity/Assets/spine-unity/Editor/SkeletonDataAssetInspector.cs, spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs, spine-unity/Assets/spine-unity/SkeletonDataAsset.cs, spine-unity/Assets/spine-unity/SkeletonRenderer.cs, spine-unity/Assets/spine-unity/SpriteCollectionAttachmentLoader.cs, spine-unity/Assets/spine-unity/SpriteCollectionAttachmentLoader.cs.meta
added SPINE_TK2D compiler directive
added PreferenceItem GUI to SpineEditorUtilities
=> Added TK2D support directly to spine-unity runtime

spine-unity/Assets/spine-unity/Editor/SkeletonRendererInspector.cs, spine-unity/Assets/spine-unity/SkeletonRenderer.cs, spine-unity/Assets/spine-unity/SkeletonUtility/Editor/SkeletonUtilitySubmeshRendererInspector.cs, spine-unity/Assets/spine-unity/SkeletonUtility/Editor/SkeletonUtilitySubmeshRendererInspector.cs.meta, spine-unity/Assets/spine-unity/SkeletonUtility/SkeletonUtility.cs, spine-unity/Assets/spine-unity/SkeletonUtility/SkeletonUtilitySubmeshRenderer.cs
Needs more work, but this should function in the mean time.
=> Temporary patchjob for SkeletonUtility Submeshes

spine-unity/Assets/spine-unity/Editor/SkeletonDataAssetInspector.cs, spine-unity/Assets/spine-unity/SkeletonDataAsset.cs
Too bad SkeletonBinary is slow :(
=> Implemented SkeletonBinary for spine-unity runtimes.

spine-unity/Assets/spine-unity/Ghost.meta, spine-unity/Assets/spine-unity/Ghost/Shaders.meta, spine-unity/Assets/spine-unity/Ghost/Shaders/SkeletonGhost.shader, spine-unity/Assets/spine-unity/Ghost/Shaders/SkeletonGhost.shader.meta, spine-unity/Assets/spine-unity/Ghost/SkeletonGhost.cs, spine-unity/Assets/spine-unity/Ghost/SkeletonGhost.cs.meta, spine-unity/Assets/spine-unity/Ghost/SkeletonGhostRenderer.cs, spine-unity/Assets/spine-unity/Ghost/SkeletonGhostRenderer.cs.meta
SkeletonGhost Shader contributed by Alex Dixon
=> [Unity] Added SkeletonGhost stuff

spine-unity/Assets/spine-unity/SkeletonUtility/Editor/SkeletonUtilityBoneInspector.cs
SkeletonUtilityBoneInspector.cs updated to update obviously previously existing collider's points array.
=> [Unity] SkeletonUtilityBoneInspector.cs updated

spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs, spine-unity/Assets/spine-unity/SkeletonDataAsset.cs
Added missing semicolon for TK2D
=> [Unity] Auto-import of .skel.bytes added.

spine-unity/Assets/spine-unity/Editor/SkeletonBaker.cs, spine-unity/Assets/spine-unity/Editor/SkeletonDataAssetInspector.cs
Refactored the Mecanim and Baking options in SkeletonDataAssetInspector for clarity.
=> [Unity] Refactored the Mecanim and Baking options

spine-unity/Assets/spine-unity/SkeletonRenderer.cs
Fixes issue #481 (hopefully) and some other related issues (probably)
=> [Spine-Unity] Fix #481

spine-unity/Assets/spine-unity/SkeletonAnimator.cs
Just another fix for Mecanim weirdness.
=> [Spine-Unity] Fix occasional broken frame at the moment node transition happened

spine-csharp/src/SkeletonBinary.cs, spine-unity/Assets/Examples/Scripts/RaggedySpineboy.cs, spine-unity/Assets/spine-unity/Ragdoll/SkeletonRagdoll2D.cs
Windows Phone 8 compilation fixed (BufferedStream changed to FileStream)
RaggedySpineboy - changed fixedAngle to freezeRotation for Unity 5.1
Changed SkeletonRagdoll2D #if UNITY_5_0 to UNITY_5
=> Unity 5 and Windows Phone building fixes

spine-unity/Assets/spine-unity/SkeletonUtility/SkeletonUtilityGroundConstraint.cs
Fix for this issue: https://github.com/EsotericSoftware/spine-runtimes/issues/484
http://esotericsoftware.com/forum/Unity-IK-SkeletonUtilityGroundConstraint-problem-5464
=> [Unity] Fix GroundConstraint -y pose values

spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs
https://github.com/EsotericSoftware/spine-runtimes/pull/259
=> [Unity] Atlas ingestion safety

spine-unity/Assets/spine-unity/SkeletonRenderer.cs
http://esotericsoftware.com/forum/Flickering-and-a-solution-for-it-5299
http://esotericsoftware.com/forum/Weird-flicker-between-some-of-the-animations-5577
https://github.com/EsotericSoftware/spine-runtimes/issues/494
Also included:
Moved attachment and flip array checks outside of extra loops in CheckIfMustUpdateMeshStructure to prevent O(2n) behavior.
Renamed some identifiers. "temp" is replaced with "working". The analogy is human brain's "working memory".
Added some cached references within the method's stack (where their members are frequently accessed).
Added comments for easy update, in preparation for incoming changes in Spine v3.
=> [Unity] Fix flickering in certain cases.

spine-unity/Assets/spine-unity/Editor/SpineAttributeDrawers.cs, spine-unity/Assets/spine-unity/SpineAttributes.cs
New [SpineEventData] attribute.
Some refactoring.
=> [Unity] Property Attribute updates

spine-sfml/src/spine/spine-sfml.cpp, spine-sfml/src/spine/spine-sfml.h
* Removed include statements from the cpp
* Removed duplicate includes
* Added include statements from the cpp to the header
=> [SFML] Fixed include statments

spine-csharp/src/Atlas.cs, spine-csharp/src/SkeletonBinary.cs, spine-csharp/src/SkeletonJson.cs
Placed a !(Unity) conditional around all the unused code that causes errors in Unity UWP.
=> Unity UWP Fix

spine-unity/Assets/spine-unity/Mesh Generation/SpineMesh.cs, spine-unity/Assets/spine-unity/Modules/Ragdoll/SkeletonRagdoll2D.cs, spine-unity/Assets/spine-unity/SkeletonAnimator.cs
Added preprocessors to allow Spine to compile in Unity 4
=> Fix Unity 4 compile errors

spine-c/src/spine/Skeleton.c
based on : https://github.com/EsotericSoftware/spine-runtimes/commit/b0eec6f411fbfe88bd413151e0c9cb4f06f86115
=> [C] Transform Constraint update order fix.

spine-cocos2dx/3/src/spine/Cocos2dAttachmentLoader.cpp
=> [cocos2d-x]fix memory leak

spine-c/src/spine/MeshAttachment.c, spine-c/src/spine/SkeletonBounds.c, spine-c/src/spine/SkeletonJson.c, spine-c/src/spine/VertexAttachment.c
Hi!
We've encountered some issues with weighted meshes and I found some mistakes made in #619.
We still didn't get the stable version unfortunately :disappointed: 
I will push my ongoing changes here.
=> [spine-c] fixes with worldVerticesLength usage.

spine-js/spine.js
The hero animation doesn't play properly without these changes.
=> Fixes for threejs example

spine-unity/Assets/spine-unity/Modules/BoundingBoxFollower/BoundingBoxFollower.cs, spine-unity/Assets/spine-unity/Modules/BoundingBoxFollower/Editor/BoundingBoxFollowerInspector.cs
Added the IsTrigger property to BoundingBoxFollower and BoundingBoxFollower editor.
=> [Unity] Added BoundingBoxFollower.isTrigger

spine-cocos2dx/src/spine/spine-cocos2dx.cpp
Avoid unnecessary memory alloc & copy
=> #Use Data::takeBuffer replace deep copy data.

spine-cocos2dx/src/spine/SkeletonAnimation.cpp, spine-cocos2dx/src/spine/SkeletonAnimation.h, spine-cocos2dx/src/spine/SkeletonBatch.cpp
and it also...:
- it simplifies the constructors/initializors
- the binary API is ::createWithBinaryFile()
- the JSON API is :: createWithJsonFile()
- the old API ::createWithDataFile() is deprecated and calls
createWithJsonFile()
=> Adds Binary support to cocos2d-x

spine-csharp/src/Bone.cs
http://esotericsoftware.com/forum/Flipped-bones-during-runtime-using-XNA-sample-project-7873
=> [csharp] Fix disabled inheritance when yDown==true

spine-unity/Assets/spine-unity/SkeletonAnimator.cs
by recalculating normalized time
=> [unity]SkeletonAnimator support negative animator state speed
